import Head from 'next/head'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import Products from '../components/Products'
import Slider from '../components/Slider'
import Socials from '../components/Socials'
import { SliderData } from '../components/SliderData'
import Services from '../components/Services'
import Cookie from '../components/Cookie'
import Contact from '../components/Contact'
import Maps from '../components/Maps'

export default function Home() {

  return (
    <div className='overflow-x-hidden'>
      <Head>
        <title>Template1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero heading='Klesarstvo Kirinec Dejan' message='Slogan/O firmi'/>
      <Services />
      <Products />
      <Slider slides={SliderData} />
      <Contact />
      <Maps />
      <Socials />
      <Cookie />
    </div>
  )
}
